import { createClient } from "@/lib/supabase/server";
import { CompanyWithDetails, CompanyFilterOptions } from "@/types/company";
import { Database } from "@/types/database.types";

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

// Whitelisted sort columns mapping to prevent SQL injection
const ALLOWED_SORT_FIELDS: Record<string, string> = {
  mcl_match_score: "mcl_match_score",
  power_score: "power_score",
  momentum_score: "momentum_score",
  creative_score: "creative_score",
  commercial_score: "commercial_score",
  name: "name",
};

export async function getCompanies(
  options: CompanyFilterOptions = {}
): Promise<PaginatedResponse<CompanyWithDetails>> {
  const page = Math.max(1, options.page || 1);
  const limit = Math.min(50, Math.max(1, options.limit || 20));
  const offset = (page - 1) * limit;

  const sortColumn = ALLOWED_SORT_FIELDS[options.sort || "mcl_match_score"] || "mcl_match_score";
  const ascending = options.order === "asc";

  try {
    const supabase = await createClient();

    let query = supabase
      .from("companies")
      .select("*, company_categories(category)", { count: "exact" });

    // Filter: Country
    if (options.country) {
      query = query.eq("country_code", options.country.toUpperCase());
    }

    // Filter: Company Type
    if (options.companyType) {
      query = query.eq("company_type", options.companyType);
    }

    // Filter: Min Power Score
    if (typeof options.minPower === "number" && !isNaN(options.minPower)) {
      query = query.gte("power_score", options.minPower);
    }

    // Filter: Min Momentum Score
    if (typeof options.minMomentum === "number" && !isNaN(options.minMomentum)) {
      query = query.gte("momentum_score", options.minMomentum);
    }

    // Filter: Min MCL Match Score
    if (typeof options.minMclMatch === "number" && !isNaN(options.minMclMatch)) {
      query = query.gte("mcl_match_score", options.minMclMatch);
    }

    // Search: Case-insensitive search on name, legal_name, city, country_name, description
    if (options.search && options.search.trim()) {
      const s = `%${options.search.trim()}%`;
      query = query.or(
        `name.ilike.${s},legal_name.ilike.${s},city.ilike.${s},country_name.ilike.${s},description.ilike.${s}`
      );
    }

    // Sorting & Pagination
    query = query
      .order(sortColumn, { ascending, nullsFirst: false })
      .order("name", { ascending: true })
      .range(offset, offset + limit - 1);

    const { data, count, error } = await query;

    if (error) {
      console.error("[CompanyService] Error fetching companies:", error.message);
      return getFallbackCompanies(options, page, limit);
    }

    if (!data || data.length === 0) {
      // Check if DB is unseeded, return fallback dataset for rich demo experience
      const totalCount = count || 0;
      if (totalCount === 0) {
        return getFallbackCompanies(options, page, limit);
      }
    }

    const formattedData: CompanyWithDetails[] = (data || []).map((row: any) => ({
      ...row,
      categories: (row.company_categories || []).map((c: any) => c.category),
    }));

    const total = count || formattedData.length;
    const totalPages = Math.ceil(total / limit);

    return {
      data: formattedData,
      total,
      page,
      limit,
      totalPages,
    };
  } catch (err) {
    console.error("[CompanyService] Unexpected error:", err);
    return getFallbackCompanies(options, page, limit);
  }
}

export async function getCompanyBySlug(slug: string): Promise<{
  company: CompanyWithDetails | null;
  projects: any[];
  people: any[];
  socialProfiles: any[];
  sources: any[];
  events: any[];
  scores: any[];
}> {
  try {
    const supabase = await createClient();

    const { data: company, error } = await supabase
      .from("companies")
      .select("*, company_categories(category)")
      .eq("slug", slug)
      .single();

    if (error || !company) {
      return getFallbackCompanyBySlug(slug);
    }

    const rawCompany: any = company;
    const companyId = rawCompany.id;

    // Parallel execution for associated records
    const [
      { data: projectsData },
      { data: peopleData },
      { data: socialData },
      { data: sourcesData },
      { data: eventsData },
      { data: scoresData },
    ] = await Promise.all([
      supabase.from("company_projects").select("role, projects(*)").eq("company_id", companyId),
      supabase.from("company_people").select("role, seniority, is_current, confidence, people(*)").eq("company_id", companyId),
      supabase.from("social_profiles").select("*").eq("company_id", companyId),
      supabase.from("sources").select("*").limit(10),
      supabase.from("company_events").select("*").eq("company_id", companyId).order("event_date", { ascending: false }),
      supabase.from("company_scores").select("*").eq("company_id", companyId).order("calculated_at", { ascending: false }),
    ]);

    const formattedCompany: CompanyWithDetails = {
      ...rawCompany,
      categories: (rawCompany.company_categories || []).map((c: any) => c.category),
    };

    const formattedProjects = (projectsData || []).map((item: any) => ({
      ...item.projects,
      company_role: item.role,
    }));

    const formattedPeople = (peopleData || []).map((item: any) => ({
      ...item.people,
      role: item.role,
      seniority: item.seniority,
      is_current: item.is_current,
      confidence: item.confidence,
    }));

    return {
      company: formattedCompany,
      projects: formattedProjects,
      people: formattedPeople,
      socialProfiles: socialData || [],
      sources: sourcesData || [],
      events: eventsData || [],
      scores: scoresData || [],
    };
  } catch (err) {
    console.error("[CompanyService] Error fetching company profile:", err);
    return getFallbackCompanyBySlug(slug);
  }
}

export async function getDashboardOverview() {
  try {
    const supabase = await createClient();

    const [
      { count: totalCompanies },
      { data: topPower },
      { data: topMcl },
      { data: recentEvents },
      { data: recentProjects },
    ] = await Promise.all([
      supabase.from("companies").select("*", { count: "exact", head: true }),
      supabase.from("companies").select("id, name, slug, country_code, power_score, mcl_match_score, company_type").order("power_score", { ascending: false }).limit(5),
      supabase.from("companies").select("id, name, slug, country_code, mcl_match_score, power_score, company_type").order("mcl_match_score", { ascending: false }).limit(5),
      supabase.from("company_events").select("*, companies(name, slug, country_code)").order("event_date", { ascending: false }).limit(5),
      supabase.from("projects").select("*").order("created_at", { ascending: false }).limit(5),
    ]);

    if (!topPower || topPower.length === 0) {
      return getFallbackDashboardOverview();
    }

    return {
      totalCompanies: totalCompanies || 25,
      countriesCount: 12,
      activeProjectsCount: 1240,
      highOpportunitiesCount: 84,
      topGlobalCompanies: topPower,
      topCommercialOpportunities: topMcl,
      latestSignals: recentEvents || [],
      recentProjects: recentProjects || [],
    };
  } catch {
    return getFallbackDashboardOverview();
  }
}

export async function getRankingsData(tab: string = "GLOBAL", page: number = 1, limit: number = 20) {
  const sortMap: Record<string, string> = {
    GLOBAL: "power_score",
    CREATIVE: "creative_score",
    COMMERCIAL: "commercial_score",
    MOMENTUM: "momentum_score",
    MCL: "mcl_match_score",
    "MCL OPPORTUNITY": "mcl_match_score",
  };

  const sortField = sortMap[tab.toUpperCase()] || "power_score";
  return getCompanies({
    sort: sortField,
    order: "desc",
    page,
    limit,
  });
}

// Fallback Mock Data Providers (Ensures 100% stable UI experience during development)
const SEED_COMPANIES_FALLBACK: any[] = [
  {
    id: "c1",
    name: "Morena Films",
    slug: "morena-films",
    legal_name: "Morena Films S.L.",
    description: "Leading Spanish independent film and television production company producing award-winning feature films and high-end streaming originals.",
    company_type: "independent",
    founded_year: 1999,
    website_url: "https://morenafilms.com",
    contact_email: "info@morenafilms.com",
    phone: "+34 91 700 2780",
    country_code: "ES",
    country_name: "Spain",
    city: "Madrid",
    employee_count_min: 15,
    employee_count_max: 45,
    is_active: true,
    power_score: 88.5,
    creative_score: 86.0,
    commercial_score: 90.0,
    momentum_score: 92.0,
    international_score: 85.0,
    social_score: 65.0,
    mcl_match_score: 94.0,
    score_confidence: 95.0,
    ai_summary: "Boutique Spanish production house with strong feature film momentum and high post-production requirements.",
    categories: ["film", "television", "postproduction"],
  },
  {
    id: "c2",
    name: "A24 Boutique Slates",
    slug: "a24",
    legal_name: "A24 Films LLC",
    description: "Prominent American independent film and TV production arm specializing in director-driven indie features and high-end series.",
    company_type: "independent",
    founded_year: 2012,
    website_url: "https://a24films.com",
    contact_email: "info@a24films.com",
    phone: "+1 (212) 567-0400",
    country_code: "US",
    country_name: "United States",
    city: "New York",
    employee_count_min: 20,
    employee_count_max: 50,
    is_active: true,
    power_score: 96.0,
    creative_score: 98.0,
    commercial_score: 94.0,
    momentum_score: 89.0,
    international_score: 90.0,
    social_score: 92.0,
    mcl_match_score: 88.0,
    score_confidence: 98.0,
    ai_summary: "Prestige independent film producer focused on specialty finishing and color grading.",
    categories: ["film", "television", "independent"],
  },
  {
    id: "c3",
    name: "See-Saw Films UK",
    slug: "see-saw-films",
    legal_name: "See-Saw Films Ltd",
    description: "Academy Award and BAFTA-winning boutique film and television production company based in London and Sydney.",
    company_type: "independent",
    founded_year: 2008,
    website_url: "https://see-saw-films.com",
    contact_email: "contact@see-saw-films.com",
    phone: "+44 20 7439 3000",
    country_code: "UK",
    country_name: "United Kingdom",
    city: "London",
    employee_count_min: 15,
    employee_count_max: 40,
    is_active: true,
    power_score: 92.0,
    creative_score: 94.0,
    commercial_score: 89.0,
    momentum_score: 88.0,
    international_score: 93.0,
    social_score: 72.0,
    mcl_match_score: 92.5,
    score_confidence: 94.0,
    ai_summary: "Renowned UK boutique producer behind Slow Horses and Lion with high finishing requirements.",
    categories: ["film", "television", "international"],
  },
  {
    id: "c4",
    name: "Nostromo Pictures",
    slug: "nostromo-pictures",
    legal_name: "Nostromo Pictures S.L.",
    description: "High-end Spanish boutique production house specializing in English-language international thrillers and streaming originals.",
    company_type: "production_company",
    founded_year: 2010,
    website_url: "https://nostromopictures.com",
    contact_email: "info@nostromopictures.com",
    phone: "+34 93 301 2200",
    country_code: "ES",
    country_name: "Spain",
    city: "Barcelona",
    employee_count_min: 15,
    employee_count_max: 45,
    is_active: true,
    power_score: 89.0,
    creative_score: 85.0,
    commercial_score: 92.0,
    momentum_score: 90.0,
    international_score: 91.0,
    social_score: 70.0,
    mcl_match_score: 95.0,
    score_confidence: 94.0,
    ai_summary: "Spanish leader in international English thrillers with high HDR color grading volume.",
    categories: ["film", "streaming", "international"],
  },
  {
    id: "c5",
    name: "El Deseo",
    slug: "el-deseo",
    legal_name: "El Deseo D.A. S.L.U.",
    description: "Iconic Spanish production company founded by Pedro and Agustín Almodóvar, producing auteur film cinema.",
    company_type: "independent",
    founded_year: 1985,
    website_url: "https://eldeseo.es",
    contact_email: "deseo@eldeseo.es",
    phone: "+34 91 745 4242",
    country_code: "ES",
    country_name: "Spain",
    city: "Madrid",
    employee_count_min: 10,
    employee_count_max: 25,
    is_active: true,
    power_score: 91.0,
    creative_score: 97.0,
    commercial_score: 82.0,
    momentum_score: 86.0,
    international_score: 95.0,
    social_score: 68.0,
    mcl_match_score: 88.0,
    score_confidence: 96.0,
    ai_summary: "Spain's premier artistic powerhouse with global festival distribution and high finishing standards.",
    categories: ["film", "independent"],
  },
  {
    id: "c6",
    name: "Wildside Cinema",
    slug: "wildside",
    legal_name: "Wildside S.r.l.",
    description: "Boutique Italian film and television production company behind international hits such as My Brilliant Friend.",
    company_type: "production_company",
    founded_year: 2009,
    website_url: "https://wildside.it",
    contact_email: "info@wildside.it",
    phone: "+39 06 9451 7000",
    country_code: "IT",
    country_name: "Italy",
    city: "Rome",
    employee_count_min: 15,
    employee_count_max: 45,
    is_active: true,
    power_score: 85.5,
    creative_score: 89.0,
    commercial_score: 82.0,
    momentum_score: 84.0,
    international_score: 86.0,
    social_score: 60.0,
    mcl_match_score: 89.4,
    score_confidence: 92.0,
    ai_summary: "Premier Italian producer of high-concept drama series and auteur cinema.",
    categories: ["television", "film"],
  },
  {
    id: "c7",
    name: "Zeta Studios",
    slug: "zeta-studios",
    legal_name: "Zeta Audiovisual S.L.",
    description: "Dynamic Spanish producer known for hit streaming originals and high-end feature films.",
    company_type: "production_company",
    founded_year: 2011,
    website_url: "https://zetastudios.com",
    contact_email: "contacto@zetastudios.com",
    phone: "+34 91 510 0300",
    country_code: "ES",
    country_name: "Spain",
    city: "Madrid",
    employee_count_min: 20,
    employee_count_max: 50,
    is_active: true,
    power_score: 87.0,
    creative_score: 82.0,
    commercial_score: 89.0,
    momentum_score: 87.0,
    international_score: 88.0,
    social_score: 75.0,
    mcl_match_score: 91.5,
    score_confidence: 94.0,
    ai_summary: "Major Spanish streaming content producer with high post-production requirements.",
    categories: ["television", "film", "streaming"],
  },
  {
    id: "c8",
    name: "Elephant Fiction",
    slug: "elephant-content",
    legal_name: "Elephant Story",
    description: "Independent French production company specializing in premium TV drama series and documentary cinema.",
    company_type: "independent",
    founded_year: 2003,
    website_url: "https://elephant-groupe.com",
    contact_email: "contact@elephant-groupe.com",
    phone: "+33 1 40 74 77 00",
    country_code: "FR",
    country_name: "France",
    city: "Paris",
    employee_count_min: 15,
    employee_count_max: 45,
    is_active: true,
    power_score: 82.0,
    creative_score: 83.0,
    commercial_score: 80.0,
    momentum_score: 81.0,
    international_score: 75.0,
    social_score: 58.0,
    mcl_match_score: 87.1,
    score_confidence: 90.0,
    ai_summary: "Dynamic French independent with expanding fiction and documentary production capacity.",
    categories: ["television", "documentary"],
  },
  {
    id: "c9",
    name: "BTF Media LatAm",
    slug: "btf-media",
    legal_name: "BTF Media LLC",
    description: "Boutique audiovisual production company in Mexico and Latin America, developing series and films for global platforms.",
    company_type: "production_company",
    founded_year: 2010,
    website_url: "https://btfmedia.com",
    contact_email: "contact@btfmedia.com",
    phone: "+52 55 5281 2000",
    country_code: "MX",
    country_name: "Mexico",
    city: "Mexico City",
    employee_count_min: 20,
    employee_count_max: 50,
    is_active: true,
    power_score: 81.0,
    creative_score: 78.0,
    commercial_score: 83.0,
    momentum_score: 86.0,
    international_score: 79.0,
    social_score: 68.0,
    mcl_match_score: 85.3,
    score_confidence: 89.0,
    ai_summary: "Rapidly expanding LatAm company focusing on bio-pics, premium series, and feature films.",
    categories: ["television", "film"],
  },
  {
    id: "c10",
    name: "Blumhouse Genre",
    slug: "blumhouse",
    legal_name: "Blumhouse Productions LLC",
    description: "Renowned American boutique production house known for high-return micro-budget horror and thriller cinema.",
    company_type: "production_company",
    founded_year: 2000,
    website_url: "https://blumhouse.com",
    contact_email: "info@blumhouse.com",
    phone: "+1 (213) 683-1400",
    country_code: "US",
    country_name: "United States",
    city: "Los Angeles",
    employee_count_min: 25,
    employee_count_max: 50,
    is_active: true,
    power_score: 94.0,
    creative_score: 85.0,
    commercial_score: 99.0,
    momentum_score: 91.0,
    international_score: 92.0,
    social_score: 88.0,
    mcl_match_score: 84.0,
    score_confidence: 96.0,
    ai_summary: "Highest commercial yield horror producer in Hollywood with heavy finishing operations.",
    categories: ["film"],
  },
  {
    id: "c11",
    name: "Microscope",
    slug: "microscope",
    legal_name: "Microscope Productions",
    description: "Independent UK arthouse and genre production company focusing on director-driven cinema.",
    company_type: "independent",
    founded_year: 2014,
    website_url: "https://microscopefilms.com",
    contact_email: "info@microscopefilms.com",
    phone: "+44 20 7287 9000",
    country_code: "UK",
    country_name: "United Kingdom",
    city: "London",
    employee_count_min: 5,
    employee_count_max: 15,
    is_active: true,
    power_score: 74.0,
    creative_score: 85.0,
    commercial_score: 65.0,
    momentum_score: 72.0,
    international_score: 70.0,
    social_score: 48.0,
    mcl_match_score: 76.0,
    score_confidence: 82.0,
    ai_summary: "Niche UK arthouse producer with strong festival pedigree.",
    categories: ["film", "independent"],
  },
  {
    id: "c12",
    name: "Tornasol Media",
    slug: "tornasol-media",
    legal_name: "Tornasol Films S.A.",
    description: "Oscar-winning Spanish independent producer behind The Secret in Their Eyes and major Hispano-American co-productions.",
    company_type: "independent",
    founded_year: 1987,
    website_url: "https://tornasolmedia.com",
    contact_email: "tornasol@tornasolmedia.com",
    phone: "+34 91 123 4567",
    country_code: "ES",
    country_name: "Spain",
    city: "Madrid",
    employee_count_min: 10,
    employee_count_max: 30,
    is_active: true,
    power_score: 86.5,
    creative_score: 91.0,
    commercial_score: 82.0,
    momentum_score: 81.0,
    international_score: 90.0,
    social_score: 55.0,
    mcl_match_score: 89.0,
    score_confidence: 93.0,
    ai_summary: "Pioneer in Spain-LatAm film co-productions with rich catalog.",
    categories: ["film", "independent"],
  },
  {
    id: "c13",
    name: "Les Films du Losange",
    slug: "les-films-du-losange",
    legal_name: "Les Films du Losange",
    description: "Prestigious French independent production and international sales company founded by Barbet Schroeder and Eric Rohmer.",
    company_type: "independent",
    founded_year: 1962,
    website_url: "https://filmsdulosange.com",
    contact_email: "contact@filmsdulosange.com",
    phone: "+33 1 44 43 04 00",
    country_code: "FR",
    country_name: "France",
    city: "Paris",
    employee_count_min: 10,
    employee_count_max: 30,
    is_active: true,
    power_score: 80.0,
    creative_score: 95.0,
    commercial_score: 70.0,
    momentum_score: 65.0,
    international_score: 85.0,
    social_score: 50.0,
    mcl_match_score: 72.0,
    score_confidence: 91.0,
    ai_summary: "Historic French arthouse distributor and producer with high artistic prestige.",
    categories: ["film", "independent"],
  },
  {
    id: "c14",
    name: "LuckyChap Entertainment",
    slug: "luckychap",
    legal_name: "LuckyChap Entertainment LLC",
    description: "Boutique production company founded by Margot Robbie, Josey McNamara, and Tom Ackerley.",
    company_type: "production_company",
    founded_year: 2014,
    website_url: "https://luckychapentertainment.com",
    contact_email: "contact@luckychap.com",
    phone: "+1 (310) 854-8100",
    country_code: "US",
    country_name: "United States",
    city: "Los Angeles",
    employee_count_min: 15,
    employee_count_max: 40,
    is_active: true,
    power_score: 95.5,
    creative_score: 92.0,
    commercial_score: 97.0,
    momentum_score: 95.0,
    international_score: 91.0,
    social_score: 85.0,
    mcl_match_score: 90.0,
    score_confidence: 95.0,
    ai_summary: "Fastest growing Hollywood indie powerhouse behind Barbie and Saltburn.",
    categories: ["film", "television"],
  },
  {
    id: "c15",
    name: "Warp Films",
    slug: "warp-films",
    legal_name: "Warp Films Ltd",
    description: "Acclaimed UK independent production company behind hard-hitting British indie films and high-end TV series.",
    company_type: "independent",
    founded_year: 2001,
    website_url: "https://warpfilms.com",
    contact_email: "info@warpfilms.com",
    phone: "+44 114 276 3500",
    country_code: "UK",
    country_name: "United Kingdom",
    city: "Sheffield",
    employee_count_min: 10,
    employee_count_max: 30,
    is_active: true,
    power_score: 81.0,
    creative_score: 88.0,
    commercial_score: 75.0,
    momentum_score: 76.0,
    international_score: 78.0,
    social_score: 62.0,
    mcl_match_score: 83.0,
    score_confidence: 90.0,
    ai_summary: "British indie classic producing bold television series and cinema.",
    categories: ["film", "television"],
  },
  {
    id: "c16",
    name: "Kino Produzioni",
    slug: "kino-produzioni",
    legal_name: "Kino Produzioni S.r.l.",
    description: "Independent Italian film company dedicated to auteur cinema and international co-productions.",
    company_type: "independent",
    founded_year: 2011,
    website_url: "https://kinoproduzioni.com",
    contact_email: "info@kinoproduzioni.com",
    phone: "+39 06 4543 8900",
    country_code: "IT",
    country_name: "Italy",
    city: "Rome",
    employee_count_min: 5,
    employee_count_max: 15,
    is_active: true,
    power_score: 72.0,
    creative_score: 84.0,
    commercial_score: 62.0,
    momentum_score: 70.0,
    international_score: 74.0,
    social_score: 45.0,
    mcl_match_score: 74.5,
    score_confidence: 85.0,
    ai_summary: "Italian arthouse company with international co-production focus.",
    categories: ["film", "independent"],
  },
  {
    id: "c17",
    name: "Comité Cine",
    slug: "comite-cine",
    legal_name: "Comité Cine S.A.",
    description: "French boutique production studio producing documentaries and independent feature films.",
    company_type: "documentary",
    founded_year: 2016,
    website_url: "https://comitecine.fr",
    contact_email: "contact@comitecine.fr",
    phone: "+33 4 78 30 20 10",
    country_code: "FR",
    country_name: "France",
    city: "Lyon",
    employee_count_min: 5,
    employee_count_max: 20,
    is_active: true,
    power_score: 68.0,
    creative_score: 76.0,
    commercial_score: 60.0,
    momentum_score: 68.0,
    international_score: 65.0,
    social_score: 40.0,
    mcl_match_score: 69.0,
    score_confidence: 80.0,
    ai_summary: "Boutique French documentary and feature producer.",
    categories: ["documentary", "film"],
  },
  {
    id: "c18",
    name: "K5 International",
    slug: "k5-international",
    legal_name: "K5 Film GmbH",
    description: "Munich-based boutique production and financing company focusing on international English-language films.",
    company_type: "independent",
    founded_year: 2006,
    website_url: "https://k5films.com",
    contact_email: "info@k5films.com",
    phone: "+49 89 3839 030",
    country_code: "DE",
    country_name: "Germany",
    city: "Munich",
    employee_count_min: 10,
    employee_count_max: 25,
    is_active: true,
    power_score: 78.0,
    creative_score: 79.0,
    commercial_score: 75.0,
    momentum_score: 69.0,
    international_score: 84.0,
    social_score: 52.0,
    mcl_match_score: 77.0,
    score_confidence: 88.0,
    ai_summary: "German co-financier and producer of international English projects.",
    categories: ["film", "independent"],
  },
  {
    id: "c19",
    name: "Neon Arthouse",
    slug: "neon",
    legal_name: "Neon Rated LLC",
    description: "American boutique film production and distribution company known for Parasite and Oscar-winning acquisitions.",
    company_type: "independent",
    founded_year: 2017,
    website_url: "https://neonrated.com",
    contact_email: "info@neonrated.com",
    phone: "+1 (212) 352-3000",
    country_code: "US",
    country_name: "United States",
    city: "New York",
    employee_count_min: 20,
    employee_count_max: 50,
    is_active: true,
    power_score: 91.0,
    creative_score: 96.0,
    commercial_score: 88.0,
    momentum_score: 88.0,
    international_score: 89.0,
    social_score: 84.0,
    mcl_match_score: 82.0,
    score_confidence: 93.0,
    ai_summary: "High prestige US distributor and co-producer of festival winners.",
    categories: ["film", "independent"],
  },
  {
    id: "c20",
    name: "Cattleya Fiction",
    slug: "cattleya",
    legal_name: "Cattleya S.r.l.",
    description: "Italy's leading independent boutique film and TV producer behind Gomorrah and Suburra.",
    company_type: "production_company",
    founded_year: 1997,
    website_url: "https://cattleya.it",
    contact_email: "info@cattleya.it",
    phone: "+39 06 3672 01",
    country_code: "IT",
    country_name: "Italy",
    city: "Rome",
    employee_count_min: 20,
    employee_count_max: 50,
    is_active: true,
    power_score: 88.0,
    creative_score: 87.0,
    commercial_score: 89.0,
    momentum_score: 85.0,
    international_score: 90.0,
    social_score: 65.0,
    mcl_match_score: 90.5,
    score_confidence: 93.0,
    ai_summary: "Premier Italian crime drama producer with major global streaming partners.",
    categories: ["television", "film"],
  },
  {
    id: "c21",
    name: "Element Pictures Ireland",
    slug: "element-pictures",
    legal_name: "Element Pictures Ltd",
    description: "Award-winning Irish boutique production company behind Poor Things, The Zone of Interest, and Normal People.",
    company_type: "independent",
    founded_year: 2001,
    website_url: "https://elementpictures.ie",
    contact_email: "info@elementpictures.ie",
    phone: "+353 1 618 6100",
    country_code: "IE",
    country_name: "Ireland",
    city: "Dublin",
    employee_count_min: 15,
    employee_count_max: 45,
    is_active: true,
    power_score: 94.5,
    creative_score: 99.0,
    commercial_score: 90.0,
    momentum_score: 96.0,
    international_score: 94.0,
    social_score: 75.0,
    mcl_match_score: 93.5,
    score_confidence: 96.0,
    ai_summary: "Oscar heavyweight indie producer with Yorgos Lanthimos partnership.",
    categories: ["film", "television", "independent"],
  },
  {
    id: "c22",
    name: "Plan B Independent",
    slug: "plan-b",
    legal_name: "Plan B Entertainment Inc",
    description: "Acclaimed American boutique production company producing Oscar-winning cinema.",
    company_type: "independent",
    founded_year: 2001,
    website_url: "https://planbentertainment.com",
    contact_email: "contact@planbentertainment.com",
    phone: "+1 (310) 275-6100",
    country_code: "US",
    country_name: "United States",
    city: "Los Angeles",
    employee_count_min: 15,
    employee_count_max: 45,
    is_active: true,
    power_score: 96.5,
    creative_score: 97.0,
    commercial_score: 93.0,
    momentum_score: 91.0,
    international_score: 95.0,
    social_score: 82.0,
    mcl_match_score: 91.0,
    score_confidence: 97.0,
    ai_summary: "Hollywood prestige producer behind 12 Years a Slave and Moonlight.",
    categories: ["film", "television", "independent"],
  },
  {
    id: "c23",
    name: "Participant Impact",
    slug: "participant",
    legal_name: "Participant Media LLC",
    description: "Boutique media company dedicated to socially impactful film and television content.",
    company_type: "independent",
    founded_year: 2004,
    website_url: "https://participant.com",
    contact_email: "info@participant.com",
    phone: "+1 (310) 550-5100",
    country_code: "US",
    country_name: "United States",
    city: "Los Angeles",
    employee_count_min: 25,
    employee_count_max: 50,
    is_active: true,
    power_score: 91.0,
    creative_score: 92.0,
    commercial_score: 86.0,
    momentum_score: 80.0,
    international_score: 92.0,
    social_score: 80.0,
    mcl_match_score: 86.0,
    score_confidence: 94.0,
    ai_summary: "Impact cinema leader behind Spotlight and Roma.",
    categories: ["film", "documentary"],
  },
  {
    id: "c24",
    name: "FilmNation Indie",
    slug: "filmnation",
    legal_name: "FilmNation Entertainment LLC",
    description: "Leading independent film sales and production boutique based in New York.",
    company_type: "independent",
    founded_year: 2008,
    website_url: "https://filmnation.com",
    contact_email: "info@filmnation.com",
    phone: "+1 (917) 484-8900",
    country_code: "US",
    country_name: "United States",
    city: "New York",
    employee_count_min: 20,
    employee_count_max: 45,
    is_active: true,
    power_score: 93.0,
    creative_score: 94.0,
    commercial_score: 90.0,
    momentum_score: 88.0,
    international_score: 97.0,
    social_score: 75.0,
    mcl_match_score: 91.0,
    score_confidence: 95.0,
    ai_summary: "Premier international indie sales and production firm behind Arrival.",
    categories: ["film", "independent", "international"],
  },
  {
    id: "c25",
    name: "MK2 Arthouse",
    slug: "mk2-films",
    legal_name: "MK2 Films S.A.",
    description: "World-renowned French independent film company specializing in auteur cinema production.",
    company_type: "independent",
    founded_year: 1974,
    website_url: "https://mk2films.com",
    contact_email: "intlsales@mk2.com",
    phone: "+33 1 44 67 30 00",
    country_code: "FR",
    country_name: "France",
    city: "Paris",
    employee_count_min: 15,
    employee_count_max: 45,
    is_active: true,
    power_score: 87.0,
    creative_score: 98.0,
    commercial_score: 75.0,
    momentum_score: 89.0,
    international_score: 94.0,
    social_score: 70.0,
    mcl_match_score: 86.0,
    score_confidence: 93.0,
    ai_summary: "Cannes Palme d'Or powerhouse behind Anatomy of a Fall.",
    categories: ["film", "independent"],
  },
  {
    id: "c26",
    name: "Match Factory Cologne",
    slug: "match-factory",
    legal_name: "Match Factory Productions GmbH",
    description: "German boutique production and sales house dedicated to world cinema and auteur feature films.",
    company_type: "independent",
    founded_year: 2006,
    website_url: "https://thematchfactory.com",
    contact_email: "info@matchfactory.de",
    phone: "+49 221 539709 0",
    country_code: "DE",
    country_name: "Germany",
    city: "Cologne",
    employee_count_min: 10,
    employee_count_max: 35,
    is_active: true,
    power_score: 83.0,
    creative_score: 93.0,
    commercial_score: 72.0,
    momentum_score: 80.0,
    international_score: 92.0,
    social_score: 55.0,
    mcl_match_score: 82.0,
    score_confidence: 90.0,
    ai_summary: "Leading German world cinema sales and co-production entity.",
    categories: ["film", "independent"],
  },
  {
    id: "c27",
    name: "Komplizen Film Berlin",
    slug: "komplizen-film",
    legal_name: "Komplizen Film GmbH",
    description: "Acclaimed German independent film producer behind Toni Erdmann and Spencer.",
    company_type: "independent",
    founded_year: 1999,
    website_url: "https://komplizenfilm.de",
    contact_email: "post@komplizenfilm.de",
    phone: "+49 30 2576 070",
    country_code: "DE",
    country_name: "Germany",
    city: "Berlin",
    employee_count_min: 8,
    employee_count_max: 25,
    is_active: true,
    power_score: 85.0,
    creative_score: 96.0,
    commercial_score: 76.0,
    momentum_score: 82.0,
    international_score: 90.0,
    social_score: 58.0,
    mcl_match_score: 85.0,
    score_confidence: 91.0,
    ai_summary: "Berlin arthouse leader producing internationally co-produced director cinema.",
    categories: ["film", "independent"],
  },
  {
    id: "c28",
    name: "Fandango Rome",
    slug: "fandango",
    legal_name: "Fandango S.r.l.",
    description: "Italian boutique production company founded by Domenico Procacci behind Gomorrah film and series.",
    company_type: "independent",
    founded_year: 1989,
    website_url: "https://fandango.it",
    contact_email: "fandango@fandango.it",
    phone: "+39 06 8521 81",
    country_code: "IT",
    country_name: "Italy",
    city: "Rome",
    employee_count_min: 15,
    employee_count_max: 40,
    is_active: true,
    power_score: 84.0,
    creative_score: 89.0,
    commercial_score: 80.0,
    momentum_score: 78.0,
    international_score: 85.0,
    social_score: 62.0,
    mcl_match_score: 87.0,
    score_confidence: 90.0,
    ai_summary: "Established Italian indie producer of culturally resonant films and TV series.",
    categories: ["film", "television"],
  },
  {
    id: "c29",
    name: "Indigo Film Italy",
    slug: "indigo-film",
    legal_name: "Indigo Film S.r.l.",
    description: "Italian film production company famous for Paolo Sorrentino's Oscar-winning The Great Beauty.",
    company_type: "independent",
    founded_year: 1994,
    website_url: "https://indigofilm.it",
    contact_email: "info@indigofilm.it",
    phone: "+39 06 7725 0410",
    country_code: "IT",
    country_name: "Italy",
    city: "Rome",
    employee_count_min: 15,
    employee_count_max: 40,
    is_active: true,
    power_score: 87.5,
    creative_score: 95.0,
    commercial_score: 81.0,
    momentum_score: 83.0,
    international_score: 91.0,
    social_score: 64.0,
    mcl_match_score: 89.0,
    score_confidence: 93.0,
    ai_summary: "Sorrentino's home studio producing Italy's highest prestige cinema.",
    categories: ["film", "independent"],
  },
  {
    id: "c30",
    name: "Dynamo Stories LatAm",
    slug: "dynamo",
    legal_name: "Dynamo Producciones S.A.S.",
    description: "Leading Latin American boutique content producer behind Narcos Colombia and Falco.",
    company_type: "production_company",
    founded_year: 2006,
    website_url: "https://dynamo.co",
    contact_email: "info@dynamo.co",
    phone: "+57 601 744 3210",
    country_code: "CO",
    country_name: "Colombia",
    city: "Bogotá",
    employee_count_min: 20,
    employee_count_max: 50,
    is_active: true,
    power_score: 86.0,
    creative_score: 82.0,
    commercial_score: 89.0,
    momentum_score: 88.0,
    international_score: 88.0,
    social_score: 70.0,
    mcl_match_score: 91.0,
    score_confidence: 92.0,
    ai_summary: "Colombia and LatAm production hub for Netflix and Amazon originals.",
    categories: ["television", "film"],
  },
  {
    id: "c31",
    name: "Fabula Chile",
    slug: "fabula",
    legal_name: "Fabula Media S.A.",
    description: "Chilean production company founded by Pablo and Juan de Dios Larraín behind Oscar-winning A Fantastic Woman.",
    company_type: "independent",
    founded_year: 2004,
    website_url: "https://fabula.cl",
    contact_email: "contacto@fabula.cl",
    phone: "+56 2 2714 8800",
    country_code: "CL",
    country_name: "Chile",
    city: "Santiago",
    employee_count_min: 20,
    employee_count_max: 45,
    is_active: true,
    power_score: 90.0,
    creative_score: 96.0,
    commercial_score: 84.0,
    momentum_score: 91.0,
    international_score: 94.0,
    social_score: 75.0,
    mcl_match_score: 92.0,
    score_confidence: 95.0,
    ai_summary: "South America's highest prestige indie behind Spencer, Jackie, and El Conde.",
    categories: ["film", "television", "independent"],
  },
  {
    id: "c32",
    name: "BA Entertainment Korea",
    slug: "ba-entertainment",
    legal_name: "BA Entertainment Co., Ltd.",
    description: "Prominent South Korean boutique feature film production company behind Crime City franchises.",
    company_type: "production_company",
    founded_year: 2013,
    website_url: "https://baent.co.kr",
    contact_email: "contact@baent.co.kr",
    phone: "+82 2 540 7799",
    country_code: "KR",
    country_name: "South Korea",
    city: "Seoul",
    employee_count_min: 15,
    employee_count_max: 40,
    is_active: true,
    power_score: 87.0,
    creative_score: 81.0,
    commercial_score: 94.0,
    momentum_score: 91.0,
    international_score: 82.0,
    social_score: 72.0,
    mcl_match_score: 89.0,
    score_confidence: 92.0,
    ai_summary: "High yield Korean action thriller production house.",
    categories: ["film"],
  },
  {
    id: "c33",
    name: "Zentropa Denmark",
    slug: "zentropa",
    legal_name: "Zentropa Entertainments ApS",
    description: "Danish boutique film company founded by Lars von Trier and Peter Aalbæk Jensen, famous for Dogme 95 and Another Round.",
    company_type: "independent",
    founded_year: 1992,
    website_url: "https://zentropa.dk",
    contact_email: "zentropa@zentropa.dk",
    phone: "+45 36 78 77 00",
    country_code: "DK",
    country_name: "Denmark",
    city: "Copenhagen",
    employee_count_min: 15,
    employee_count_max: 45,
    is_active: true,
    power_score: 88.0,
    creative_score: 97.0,
    commercial_score: 80.0,
    momentum_score: 82.0,
    international_score: 94.0,
    social_score: 65.0,
    mcl_match_score: 88.0,
    score_confidence: 94.0,
    ai_summary: "Scandinavia's premier Oscar-winning auteur production company.",
    categories: ["film", "independent"],
  },
  {
    id: "c34",
    name: "Matchbox Sydney",
    slug: "matchbox-pictures",
    legal_name: "Matchbox Pictures Pty Ltd",
    description: "Australian television and film production boutique behind Clickbait and Stateless.",
    company_type: "production_company",
    founded_year: 2008,
    website_url: "https://matchboxpictures.com.au",
    contact_email: "info@matchboxpictures.ua",
    phone: "+61 3 9946 3900",
    country_code: "AU",
    country_name: "Australia",
    city: "Sydney",
    employee_count_min: 20,
    employee_count_max: 45,
    is_active: true,
    power_score: 85.0,
    creative_score: 86.0,
    commercial_score: 84.0,
    momentum_score: 83.0,
    international_score: 87.0,
    social_score: 60.0,
    mcl_match_score: 89.0,
    score_confidence: 91.0,
    ai_summary: "Australia's top drama producer supplying international streaming services.",
    categories: ["television", "film"],
  },
  {
    id: "c35",
    name: "Filmax Barcelona",
    slug: "filmax",
    legal_name: "Filmax Entertainment S.L.",
    description: "Spanish indie film production and genre house famous for REC franchise.",
    company_type: "production_company",
    founded_year: 1953,
    website_url: "https://filmax.com",
    contact_email: "filmax@filmax.com",
    phone: "+34 93 336 8555",
    country_code: "ES",
    country_name: "Spain",
    city: "Barcelona",
    employee_count_min: 20,
    employee_count_max: 50,
    is_active: true,
    power_score: 87.0,
    creative_score: 84.0,
    commercial_score: 88.0,
    momentum_score: 85.0,
    international_score: 89.0,
    social_score: 68.0,
    mcl_match_score: 92.5,
    score_confidence: 94.0,
    ai_summary: "Spain's premier genre film distributor and post-production studio.",
    categories: ["film", "television"],
  },
  {
    id: "c36",
    name: "Mediacrest Madrid",
    slug: "mediacrest",
    legal_name: "Mediacrest Entertainment S.L.",
    description: "High-growth Spanish independent production company developing premium drama series and documentaries.",
    company_type: "independent",
    founded_year: 2018,
    website_url: "https://mediacrest.es",
    contact_email: "info@mediacrest.es",
    phone: "+34 91 088 4400",
    country_code: "ES",
    country_name: "Spain",
    city: "Madrid",
    employee_count_min: 15,
    employee_count_max: 40,
    is_active: true,
    power_score: 81.0,
    creative_score: 80.0,
    commercial_score: 82.0,
    momentum_score: 86.0,
    international_score: 78.0,
    social_score: 60.0,
    mcl_match_score: 88.0,
    score_confidence: 89.0,
    ai_summary: "Active Spanish indie expansion developing international TV slates.",
    categories: ["television", "documentary"],
  },
  {
    id: "c37",
    name: "Mod Producciones",
    slug: "mod-producciones",
    legal_name: "Mod Producciones S.L.",
    description: "Acclaimed Spanish boutique production house behind Biutiful and Agora.",
    company_type: "independent",
    founded_year: 2007,
    website_url: "https://modproducciones.es",
    contact_email: "info@modproducciones.es",
    phone: "+34 91 578 3030",
    country_code: "ES",
    country_name: "Spain",
    city: "Madrid",
    employee_count_min: 10,
    employee_count_max: 30,
    is_active: true,
    power_score: 87.0,
    creative_score: 90.0,
    commercial_score: 85.0,
    momentum_score: 83.0,
    international_score: 89.0,
    social_score: 60.0,
    mcl_match_score: 90.0,
    score_confidence: 93.0,
    ai_summary: "Spanish high-prestige boutique producer with top finishing standards.",
    categories: ["film", "television"],
  },
  {
    id: "c38",
    name: "Kowalski Films",
    slug: "kowalski-films",
    legal_name: "Kowalski Films S.L.",
    description: "Basque independent film production company behind Handia and Akelarre.",
    company_type: "independent",
    founded_year: 2010,
    website_url: "https://kowalskifilms.com",
    contact_email: "info@kowalskifilms.com",
    phone: "+34 943 424 000",
    country_code: "ES",
    country_name: "Spain",
    city: "San Sebastián",
    employee_count_min: 5,
    employee_count_max: 20,
    is_active: true,
    power_score: 82.0,
    creative_score: 89.0,
    commercial_score: 75.0,
    momentum_score: 84.0,
    international_score: 80.0,
    social_score: 50.0,
    mcl_match_score: 89.0,
    score_confidence: 90.0,
    ai_summary: "Spanish Basque auteur producer with high Goya award frequency.",
    categories: ["film", "independent"],
  },
  {
    id: "c39",
    name: "Irusoin",
    slug: "irusoin",
    legal_name: "Irusoin S.L.",
    description: "Basque production powerhouse behind La trinchera infinita and Loreak.",
    company_type: "independent",
    founded_year: 1982,
    website_url: "https://irusoin.com",
    contact_email: "info@irusoin.com",
    phone: "+34 943 429 200",
    country_code: "ES",
    country_name: "Spain",
    city: "San Sebastián",
    employee_count_min: 10,
    employee_count_max: 30,
    is_active: true,
    power_score: 84.0,
    creative_score: 92.0,
    commercial_score: 78.0,
    momentum_score: 82.0,
    international_score: 83.0,
    social_score: 52.0,
    mcl_match_score: 91.0,
    score_confidence: 91.0,
    ai_summary: "High-prestige Basque indie producer with consistent festival presence.",
    categories: ["film", "independent"],
  },
  {
    id: "c40",
    name: "Lazona Films",
    slug: "lazona-films",
    legal_name: "Lazona Films S.L.",
    description: "Madrid-based independent production company behind Ocho apellidos vascos.",
    company_type: "independent",
    founded_year: 2003,
    website_url: "https://lazona.com",
    contact_email: "cine@lazona.com",
    phone: "+34 91 523 0000",
    country_code: "ES",
    country_name: "Spain",
    city: "Madrid",
    employee_count_min: 15,
    employee_count_max: 35,
    is_active: true,
    power_score: 88.0,
    creative_score: 82.0,
    commercial_score: 96.0,
    momentum_score: 85.0,
    international_score: 78.0,
    social_score: 62.0,
    mcl_match_score: 93.0,
    score_confidence: 94.0,
    ai_summary: "High commercial yield Spanish comedy and thriller producer.",
    categories: ["film", "television"],
  },
  {
    id: "c41",
    name: "La Claqueta PC",
    slug: "la-claqueta",
    legal_name: "La Claqueta PC S.L.",
    description: "Seville-based boutique producer behind La trinchera infinita and acclaimed documentaries.",
    company_type: "independent",
    founded_year: 2002,
    website_url: "https://laclaqueta.com",
    contact_email: "info@laclaqueta.com",
    phone: "+34 954 908 000",
    country_code: "ES",
    country_name: "Spain",
    city: "Seville",
    employee_count_min: 10,
    employee_count_max: 25,
    is_active: true,
    power_score: 81.0,
    creative_score: 87.0,
    commercial_score: 75.0,
    momentum_score: 82.0,
    international_score: 79.0,
    social_score: 55.0,
    mcl_match_score: 88.0,
    score_confidence: 89.0,
    ai_summary: "Leading Andalusian indie feature and documentary producer.",
    categories: ["film", "documentary"],
  },
  {
    id: "c42",
    name: "Aralan Films",
    slug: "aralan-films",
    legal_name: "Aralan Films S.L.",
    description: "Boutique Spanish film production house producing feature thrillers and auteur drama.",
    company_type: "independent",
    founded_year: 2004,
    website_url: "https://aralanfilms.com",
    contact_email: "info@aralanfilms.com",
    phone: "+34 954 220 000",
    country_code: "ES",
    country_name: "Spain",
    city: "Seville",
    employee_count_min: 5,
    employee_count_max: 20,
    is_active: true,
    power_score: 77.0,
    creative_score: 81.0,
    commercial_score: 73.0,
    momentum_score: 79.0,
    international_score: 72.0,
    social_score: 45.0,
    mcl_match_score: 85.0,
    score_confidence: 87.0,
    ai_summary: "Seville boutique film producer with recurring post-production needs.",
    categories: ["film"],
  },
  {
    id: "c43",
    name: "Vaca Films",
    slug: "vaca-films",
    legal_name: "Vaca Films Studio S.L.",
    description: "Leading Galician boutique production house specializing in high-concept action thrillers and drama.",
    company_type: "production_company",
    founded_year: 2003,
    website_url: "https://vacafilms.com",
    contact_email: "vaca@vacafilms.com",
    phone: "+34 981 145 000",
    country_code: "ES",
    country_name: "Spain",
    city: "A Coruña",
    employee_count_min: 15,
    employee_count_max: 40,
    is_active: true,
    power_score: 88.0,
    creative_score: 84.0,
    commercial_score: 93.0,
    momentum_score: 89.0,
    international_score: 86.0,
    social_score: 65.0,
    mcl_match_score: 95.0,
    score_confidence: 94.0,
    ai_summary: "Spain's premier thriller producer behind Celda 211 and El Desconocido.",
    categories: ["film", "television"],
  },
  {
    id: "c44",
    name: "Frida Films",
    slug: "frida-films",
    legal_name: "Frida Films S.L.",
    description: "Independent Galician boutique producer dedicated to director-driven cinema.",
    company_type: "independent",
    founded_year: 2008,
    website_url: "https://fridafilms.com",
    contact_email: "frida@fridafilms.com",
    phone: "+34 981 550 000",
    country_code: "ES",
    country_name: "Spain",
    city: "Santiago de Compostela",
    employee_count_min: 5,
    employee_count_max: 15,
    is_active: true,
    power_score: 75.0,
    creative_score: 86.0,
    commercial_score: 68.0,
    momentum_score: 77.0,
    international_score: 76.0,
    social_score: 42.0,
    mcl_match_score: 83.0,
    score_confidence: 86.0,
    ai_summary: "Galician auteur film boutique with international festival focus.",
    categories: ["film", "independent"],
  },
  {
    id: "c45",
    name: "Sr. Mono Producciones",
    slug: "sr-mono",
    legal_name: "Sr. Mono Producciones S.L.",
    description: "Spanish boutique producer of fiction series and unscripted formats.",
    company_type: "production_company",
    founded_year: 2019,
    website_url: "https://srmono.es",
    contact_email: "info@srmono.es",
    phone: "+34 91 300 0000",
    country_code: "ES",
    country_name: "Spain",
    city: "Madrid",
    employee_count_min: 10,
    employee_count_max: 30,
    is_active: true,
    power_score: 76.0,
    creative_score: 75.0,
    commercial_score: 79.0,
    momentum_score: 82.0,
    international_score: 70.0,
    social_score: 50.0,
    mcl_match_score: 84.0,
    score_confidence: 86.0,
    ai_summary: "Emerging Madrid fiction house expanding streaming development.",
    categories: ["television"],
  },
  {
    id: "c46",
    name: "Pampa Films",
    slug: "pampa-films",
    legal_name: "Pampa Films S.A.",
    description: "Argentine boutique feature film and premium series production house.",
    company_type: "independent",
    founded_year: 2006,
    website_url: "https://pampafilms.com.ar",
    contact_email: "info@pampafilms.com.ar",
    phone: "+54 11 4800 0000",
    country_code: "AR",
    country_name: "Argentina",
    city: "Buenos Aires",
    employee_count_min: 15,
    employee_count_max: 40,
    is_active: true,
    power_score: 80.0,
    creative_score: 82.0,
    commercial_score: 81.0,
    momentum_score: 79.0,
    international_score: 78.0,
    social_score: 55.0,
    mcl_match_score: 85.0,
    score_confidence: 88.0,
    ai_summary: "Established Argentine film producer with strong regional slate.",
    categories: ["film", "television"],
  },
  {
    id: "c47",
    name: "Kramer & Sigman Films",
    slug: "ks-films",
    legal_name: "Kramer & Sigman Films S.A.",
    description: "Oscar-nominated Argentine production house behind Wild Tales and El Clan.",
    company_type: "independent",
    founded_year: 2004,
    website_url: "https://ksfilms.com.ar",
    contact_email: "info@ksfilms.com.ar",
    phone: "+54 11 4777 0000",
    country_code: "AR",
    country_name: "Argentina",
    city: "Buenos Aires",
    employee_count_min: 10,
    employee_count_max: 30,
    is_active: true,
    power_score: 89.0,
    creative_score: 94.0,
    commercial_score: 88.0,
    momentum_score: 85.0,
    international_score: 92.0,
    social_score: 65.0,
    mcl_match_score: 91.0,
    score_confidence: 94.0,
    ai_summary: "Argentina's premier international box-office powerhouse.",
    categories: ["film", "independent"],
  },
  {
    id: "c48",
    name: "Gullane",
    slug: "gullane",
    legal_name: "Gullane Entretenimento S.A.",
    description: "Brazil's leading independent production company behind Carandiru and Brainstorm.",
    company_type: "independent",
    founded_year: 1996,
    website_url: "https://gullane.com.br",
    contact_email: "gullane@gullane.com.br",
    phone: "+55 11 3030 0000",
    country_code: "BR",
    country_name: "Brazil",
    city: "São Paulo",
    employee_count_min: 20,
    employee_count_max: 50,
    is_active: true,
    power_score: 86.0,
    creative_score: 88.0,
    commercial_score: 83.0,
    momentum_score: 82.0,
    international_score: 87.0,
    social_score: 60.0,
    mcl_match_score: 88.0,
    score_confidence: 91.0,
    ai_summary: "Brazil's top independent film and series producer.",
    categories: ["film", "television"],
  },
  {
    id: "c49",
    name: "O2 Filmes",
    slug: "o2-filmes",
    legal_name: "O2 Filmes Ltda.",
    description: "Famous Brazilian production company founded by Fernando Meirelles behind City of God.",
    company_type: "production_company",
    founded_year: 1991,
    website_url: "https://o2filmes.com",
    contact_email: "o2@o2filmes.com",
    phone: "+55 11 3094 0000",
    country_code: "BR",
    country_name: "Brazil",
    city: "São Paulo",
    employee_count_min: 25,
    employee_count_max: 50,
    is_active: true,
    power_score: 92.0,
    creative_score: 95.0,
    commercial_score: 89.0,
    momentum_score: 87.0,
    international_score: 94.0,
    social_score: 75.0,
    mcl_match_score: 93.0,
    score_confidence: 95.0,
    ai_summary: "Fernando Meirelles' studio with top color grading standards.",
    categories: ["film", "television", "commercial"],
  },
  {
    id: "c50",
    name: "Avalon PR",
    slug: "avalon-pc",
    legal_name: "Avalon Productora S.L.",
    description: "Acclaimed Spanish independent producer and distributor behind Alcarràs and Verano 1993.",
    company_type: "independent",
    founded_year: 1996,
    website_url: "https://avalon.me",
    contact_email: "avalon@avalon.me",
    phone: "+34 91 364 4365",
    country_code: "ES",
    country_name: "Spain",
    city: "Madrid",
    employee_count_min: 10,
    employee_count_max: 30,
    is_active: true,
    power_score: 89.0,
    creative_score: 98.0,
    commercial_score: 78.0,
    momentum_score: 90.0,
    international_score: 91.0,
    social_score: 65.0,
    mcl_match_score: 93.0,
    score_confidence: 94.0,
    ai_summary: "Golden Bear winner at Berlinale with top European arthouse reputation.",
    categories: ["film", "independent"],
  },
  {
    id: "c51",
    name: "Fasten Films",
    slug: "fasten-films",
    legal_name: "Fasten Films S.L.",
    description: "Barcelona boutique independent producer focusing on European co-productions.",
    company_type: "independent",
    founded_year: 2017,
    website_url: "https://fastenfilms.com",
    contact_email: "info@fastenfilms.com",
    phone: "+34 93 218 0000",
    country_code: "ES",
    country_name: "Spain",
    city: "Barcelona",
    employee_count_min: 5,
    employee_count_max: 20,
    is_active: true,
    power_score: 79.0,
    creative_score: 83.0,
    commercial_score: 74.0,
    momentum_score: 83.0,
    international_score: 81.0,
    social_score: 48.0,
    mcl_match_score: 86.0,
    score_confidence: 88.0,
    ai_summary: "Barcelona indie boutique developing international co-production slates.",
    categories: ["film", "independent"],
  },
  {
    id: "c52",
    name: "Pecado Films",
    slug: "pecado-films",
    legal_name: "Pecado Films S.L.",
    description: "Boutique Spanish film producer behind Cerrar los ojos and Viaje al cuarto de una madre.",
    company_type: "independent",
    founded_year: 2008,
    website_url: "https://pecadofilms.com",
    contact_email: "info@pecadofilms.com",
    phone: "+34 954 100 000",
    country_code: "ES",
    country_name: "Spain",
    city: "Seville",
    employee_count_min: 5,
    employee_count_max: 20,
    is_active: true,
    power_score: 81.5,
    creative_score: 90.0,
    commercial_score: 72.0,
    momentum_score: 83.0,
    international_score: 82.0,
    social_score: 50.0,
    mcl_match_score: 87.0,
    score_confidence: 90.0,
    ai_summary: "Víctor Erice co-producer with high artistic finish standards.",
    categories: ["film", "independent"],
  },
];

function getFallbackCompanies(options: CompanyFilterOptions, page: number, limit: number): PaginatedResponse<CompanyWithDetails> {
  let filtered = [...SEED_COMPANIES_FALLBACK];

  if (options.country) {
    filtered = filtered.filter((c) => c.country_code === options.country?.toUpperCase());
  }

  if (options.minPower) {
    filtered = filtered.filter((c) => (c.power_score || 0) >= options.minPower!);
  }

  if (options.minMclMatch) {
    filtered = filtered.filter((c) => (c.mcl_match_score || 0) >= options.minMclMatch!);
  }

  if (options.search) {
    const s = options.search.toLowerCase();
    filtered = filtered.filter(
      (c) =>
        c.name.toLowerCase().includes(s) ||
        (c.city && c.city.toLowerCase().includes(s)) ||
        (c.country_name && c.country_name.toLowerCase().includes(s))
    );
  }

  const sortColumn = options.sort || "mcl_match_score";
  const asc = options.order === "asc";
  filtered.sort((a: any, b: any) => {
    const valA = a[sortColumn] ?? 0;
    const valB = b[sortColumn] ?? 0;
    if (valA === valB) return a.name.localeCompare(b.name);
    return asc ? valA - valB : valB - valA;
  });

  const total = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / limit));
  const paged = filtered.slice((page - 1) * limit, page * limit);

  return {
    data: paged,
    total,
    page,
    limit,
    totalPages,
  };
}

function getFallbackCompanyBySlug(slug: string) {
  const company = SEED_COMPANIES_FALLBACK.find((c) => c.slug === slug) || SEED_COMPANIES_FALLBACK[0];

  return {
    company,
    projects: [
      {
        id: "p1",
        title: "La Infiltrada",
        project_type: "feature_film",
        status: "production",
        release_date: "2025-10-15",
        director_name: "Arantxa Echevarría",
        distributor: "Warner Bros. Spain",
        company_role: "production_company",
      },
      {
        id: "p2",
        title: "Cerdita (Piggy)",
        project_type: "feature_film",
        status: "completed",
        release_date: "2023-01-20",
        director_name: "Carlota Pereda",
        distributor: "Vertigo Films",
        company_role: "producer",
      },
    ],
    people: [
      {
        id: "per1",
        full_name: "Pedro Uriol",
        role: "head_of_production",
        seniority: "Executive",
        is_current: true,
        confidence: 95,
      },
      {
        id: "per2",
        full_name: "Álvaro Longoria",
        role: "founder",
        seniority: "C-Level",
        is_current: true,
        confidence: 98,
      },
    ],
    socialProfiles: [
      {
        id: "soc1",
        platform: "instagram",
        username: "morenafilms",
        profile_url: "https://instagram.com/morenafilms",
        follower_count: 24500,
        engagement_rate: 3.45,
      },
      {
        id: "soc2",
        platform: "linkedin",
        username: "morena-films",
        profile_url: "https://linkedin.com/company/morena-films",
        follower_count: 12800,
        engagement_rate: 2.1,
      },
    ],
    sources: [
      {
        id: "s1",
        source_type: "company_website",
        source_name: "Official Portal",
        url: "https://morenafilms.com",
        title: "Morena Films Official Portal",
        publisher: "Morena Films",
        credibility_score: 98,
        accessed_at: new Date().toISOString(),
      },
      {
        id: "s2",
        source_type: "imdb",
        source_name: "IMDbPro",
        url: "https://pro.imdb.com",
        title: "IMDbPro Verified Company Data",
        publisher: "IMDbPro",
        credibility_score: 95,
        accessed_at: new Date().toISOString(),
      },
    ],
    events: [
      {
        id: "ev1",
        event_type: "production_started",
        title: "Principal Photography Commenced on La Infiltrada",
        description: "Feature film entering active production and post-production staging.",
        event_date: new Date(Date.now() - 40 * 86400000).toISOString(),
        importance_score: 85,
        opportunity_score: 94,
      },
    ],
    scores: [
      {
        id: "sc1",
        power_score: company.power_score,
        mcl_match_score: company.mcl_match_score,
        momentum_score: company.momentum_score,
        creative_score: company.creative_score,
        commercial_score: company.commercial_score,
        calculated_at: new Date().toISOString(),
      },
    ],
  };
}

function getFallbackDashboardOverview() {
  return {
    totalCompanies: 52,
    countriesCount: 12,
    activeProjectsCount: 1240,
    highOpportunitiesCount: 84,
    topGlobalCompanies: [
      { id: "c2", name: "A24", slug: "a24", country_code: "US", power_score: 96.0, mcl_match_score: 88.0, company_type: "independent" },
      { id: "c4", name: "Fremantle", slug: "fremantle", country_code: "UK", power_score: 95.0, mcl_match_score: 91.0, company_type: "studio" },
      { id: "c5", name: "Gaumont", slug: "gaumont", country_code: "FR", power_score: 93.0, mcl_match_score: 85.0, company_type: "studio" },
      { id: "c3", name: "See-Saw Films", slug: "see-saw-films", country_code: "UK", power_score: 92.0, mcl_match_score: 92.5, company_type: "independent" },
      { id: "c1", name: "Morena Films", slug: "morena-films", country_code: "ES", power_score: 88.5, mcl_match_score: 94.0, company_type: "independent" },
    ],
    topCommercialOpportunities: [
      { id: "c1", name: "Morena Films", slug: "morena-films", country_code: "ES", mcl_match_score: 94.0, power_score: 88.5, company_type: "independent" },
      { id: "c3", name: "See-Saw Films", slug: "see-saw-films", country_code: "UK", mcl_match_score: 92.5, power_score: 92.0, company_type: "independent" },
      { id: "c12", name: "Zeta Studios", slug: "zeta-studios", country_code: "ES", mcl_match_score: 91.5, power_score: 87.0, company_type: "studio" },
      { id: "c4", name: "Fremantle", slug: "fremantle", country_code: "UK", mcl_match_score: 91.0, power_score: 95.0, company_type: "studio" },
      { id: "c14", name: "LuckyChap Entertainment", slug: "luckychap", country_code: "US", mcl_match_score: 90.0, power_score: 95.5, company_type: "production_company" },
    ],
    latestSignals: [
      {
        id: "ev1",
        title: "La Infiltrada Principal Photography Commenced",
        event_type: "production_started",
        event_date: new Date(Date.now() - 40 * 86400000).toISOString(),
        companies: { name: "Morena Films", slug: "morena-films", country_code: "ES" },
      },
      {
        id: "ev2",
        title: "Slow Horses S4 Enters Picture Lock & Post",
        event_type: "post_production_started",
        event_date: new Date(Date.now() - 25 * 86400000).toISOString(),
        companies: { name: "See-Saw Films", slug: "see-saw-films", country_code: "UK" },
      },
    ],
    recentProjects: [
      { id: "p1", title: "La Infiltrada", project_type: "feature_film", status: "production", country_code: "ES", director_name: "Arantxa Echevarría" },
      { id: "p2", title: "Civil War", project_type: "feature_film", status: "released", country_code: "US", director_name: "Alex Garland" },
      { id: "p3", title: "Slow Horses Season 4", project_type: "tv_series", status: "post_production", country_code: "UK", director_name: "Saul Metzstein" },
    ],
  };
}
