import { SignalSeverity, SignalType } from "./types";

// Signal Recency Decay Multipliers (PRD Section 11)
export const SIGNAL_RECENCY_DECAY = {
  DAYS_0_7: 1.0,
  DAYS_8_30: 0.85,
  DAYS_31_90: 0.65,
  DAYS_91_180: 0.40,
  DAYS_181_365: 0.20,
};

// Expiration Windows in Days (PRD Section 18)
export const SIGNAL_EXPIRATION_DAYS: Record<SignalType, number> = {
  NEW_PROJECT: 30,
  PROJECT_ENTERED_PRODUCTION: 45,
  PROJECT_ENTERED_POST: 45,
  PROJECT_COMPLETED: 30,
  PROJECT_RELEASED: 30,
  NEW_EXECUTIVE: 60,
  EXECUTIVE_DEPARTURE: 30,
  AWARD_WIN: 30,
  FESTIVAL_SELECTION: 30,
  DISTRIBUTION_DEAL: 45,
  STREAMING_DEAL: 45,
  INTERNATIONAL_EXPANSION: 60,
  PARTNERSHIP: 45,
  ACQUISITION: 60,
  FINANCING: 45,
  MOMENTUM_SPIKE: 30,
  MCL_OPPORTUNITY: 30,
  SCORE_CHANGE: 30,
  SOCIAL_GROWTH: 30,
  COMMERCIAL_OPPORTUNITY: 30,
};

// Base Severity Mapping (PRD Section 8)
export const SIGNAL_BASE_SEVERITY: Record<SignalType, SignalSeverity> = {
  MCL_OPPORTUNITY: "CRITICAL",
  PROJECT_ENTERED_POST: "HIGH",
  PROJECT_ENTERED_PRODUCTION: "HIGH",
  MOMENTUM_SPIKE: "HIGH",
  NEW_PROJECT: "MEDIUM",
  NEW_EXECUTIVE: "MEDIUM",
  SCORE_CHANGE: "MEDIUM",
  DISTRIBUTION_DEAL: "HIGH",
  STREAMING_DEAL: "HIGH",
  AWARD_WIN: "MEDIUM",
  FESTIVAL_SELECTION: "MEDIUM",
  PROJECT_COMPLETED: "LOW",
  PROJECT_RELEASED: "LOW",
  EXECUTIVE_DEPARTURE: "LOW",
  INTERNATIONAL_EXPANSION: "MEDIUM",
  PARTNERSHIP: "LOW",
  ACQUISITION: "HIGH",
  FINANCING: "HIGH",
  SOCIAL_GROWTH: "LOW",
  COMMERCIAL_OPPORTUNITY: "HIGH",
};
